"""add password to users

Revision ID: a1391c706461
Revises: 
Create Date: 2025-07-23 17:54:13.969697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1391c706461'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Assigment_assignment_id'), table_name='Assignment')
    op.create_index(op.f('ix_Assignment_assignment_id'), 'Assignment', ['assignment_id'], unique=False)
    op.drop_column('Invoice', 'payment_id')
    op.drop_column('Medical_history', 'date')
    op.add_column('Pet', sa.Column('img_url', sa.String(length=100), nullable=True))
    
    op.add_column('User', sa.Column('hashed_password', sa.String(), nullable=False, server_default='changeme'))
    op.alter_column('User', 'hashed_password', server_default=None)

    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('User', 'registration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('registration_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('User', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('User', 'hashed_password')
    op.drop_column('Pet', 'img_url')
    op.add_column('Medical_history', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('Invoice', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Assignment_assignment_id'), table_name='Assignment')
    op.create_index(op.f('ix_Assigment_assignment_id'), 'Assignment', ['assignment_id'], unique=False)
    # ### end Alembic commands ###
